### ISSUE TITLE
Regarding Hardware Design

### ISSUE THREAD

**Issue by DDS2144** [mheinri/OpenSourceRIS#1]
Dear Sir,

I'm currently working on hardware design using your repository and facing challenges. Could I kindly request your expert guidance on some queries? I've attached relevant files for your reference.

![Controller_PCB](https://github.com/mheinri/OpenSourceRIS/assets/142567464/876d3446-e068-448b-96cb-f07deb4e5b85)
![RF_PCB_BOTTOM](https://github.com/mheinri/OpenSourceRIS/assets/142567464/9b0dfe63-8a1c-4b71-88e8-291d78ce8c1a)
[Doubt-1 - Controller_PCB.xlsx](https://github.com/mheinri/OpenSourceRIS/files/12393408/Doubt-1.-.Controller_PCB.xlsx)
[Doubt-2 - Controller_PCB.xlsx](https://github.com/mheinri/OpenSourceRIS/files/12393409/Doubt-2.-.Controller_PCB.xlsx)
[Doubt-3 - RF_PCB.xlsx](https://github.com/mheinri/OpenSourceRIS/files/12393410/Doubt-3.-.RF_PCB.xlsx)
[Doubt-4 - RF_PCB.xlsx](https://github.com/mheinri/OpenSourceRIS/files/12393412/Doubt-4.-.RF_PCB.xlsx)

**Comment by mheinri** [comment]
Hi DDS2144 ,
there is no information on the pinhead positions as they get populated by hand. This is beacuse these parts are through-hole components rather than SMD parts.
Resistor R106 is not populated at all (n.p.), thus there is no information in the BOM.
Fiducials are only used for automatic placement of components by the pick-and-place machine, so there is also no additional information on it required.
Hope this is helpful.
Best regards!
